language: ruby
sudo: false
before_install:
  - gem install bundler
env:
  - DB=postgresql
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - bundle exec rake db:create RAILS_ENV=test
addons:
  postgresql: "9.3.5"
services:
  - postgresql
