language: ruby
version:
  - 2.1.5
before_install:
  - gem install bundler
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database grabyourpack_test;' -U postgres
services:
  - postgresql
