language: ruby
sudo: false
before_install:
  - gem install bundler
env:
  - DB=postgresql
script:
  - RAILS_ENV = test bundle exec rake --trace db:migrate test
before_script:
  - psql -c 'create database grabyourpack_test;' -U postgres
addons:
  postgresql: "9.4.1"
services:
  - postgresql
